name: KirofTix
description: "UTS Pemrograman Aplikasi Mobile - KirofTix"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # database
  sqflite: ^2.2.8+4
  path: ^1.8.3
  
  # untuk tracking versi database
  shared_preferences: ^2.2.2

  # format uang dan tanggal
  intl: ^0.18.1

  # ikon
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # assets
  assets:
    - assets/images/kiroftix.png
    - assets/images/unable.png
    - assets/images/nysm_nyd.jpg
    - assets/images/predator_badlands.jpg
    - assets/images/rental_family.jpg
    - assets/images/tbg2.jpg
    - assets/images/tlw.jpg